---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: newrelic-bundle
  namespace: newrelic
spec:
  releaseName: newrelic-bundle
  chart:
    spec:
      chart: nri-bundle
      version: 5.0.71
      sourceRef:
        kind: HelmRepository
        name: newrelic
        namespace: flux-system
  interval: 15m0s
  timeout: 10m0s
  install:
    remediation:
      retries: 3
  values:
    global:
      customSecretName: "newrelic-env"
      customSecretLicenseKey: "NEW_RELIC_LICENSE_KEY"
      lowDataMode: true
    newrelic-infrastructure:
      enabled: true
      enableProcessMetrics: true
      prefixDisplayNameWithCluster: true
      useNodeNameAsDisplayName: true
      controlPlane:
        enabled: false
      ksm:
        config:
          selector: "app.kubernetes.io/name=kube-state-metrics"
          port: "8080"
          namespace: "kube-system"
      verboseLog: false
    newrelic-logging:
      enabled: true
      endpoint: "https://log-api.eu.newrelic.com/log/v1"
      fluentBit:
        criEnabled: true
        k8sLoggingExclude: "On"
    nri-kube-events:
      enabled: true
    kube-state-metrics:
      enabled: false
---
